// Export all screens from a single file
export { default as PlayerSettingsScreen } from './PlayerSettingsScreen';
export { default as ProfilesScreen } from './ProfilesScreen';
export { default as SearchScreen } from './SearchScreen';
export { default as SettingsScreen } from './SettingsScreen';
export { default as ShowRatingsScreen } from './ShowRatingsScreen';
export { default as StreamsScreen } from './StreamsScreen';
export { default as ThemeScreen } from './ThemeScreen';
export { default as TMDBSettingsScreen } from './TMDBSettingsScreen';
export { default as TraktSettingsScreen } from './TraktSettingsScreen';
export { default as PluginsScreen } from './PluginsScreen'; 