import { StyleSheet, Platform } from 'react-native';
import { SCREEN_WIDTH, HERO_HEIGHT, MOVIE_TITLE_HEIGHT } from './constants';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: 'transparent',
      ...(Platform.OS === 'ios' && {
        opacity: 1,
        shouldRasterizeIOS: false,
        renderToHardwareTextureAndroid: false,
      }),
    },
    backButtonContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 2,
      pointerEvents: 'box-none',
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingTop: Platform.OS === 'android' ? 45 : 15,
      backgroundColor: 'transparent',
    },
    backButtonText: {
      color: colors.highEmphasis,
      fontSize: 13,
      fontWeight: '600',
    },
    streamsMainContent: {
      flex: 1,
      backgroundColor: 'transparent',
      paddingTop: 12,
      zIndex: 1,
      ...(Platform.OS === 'ios' && {
        opacity: 1,
        shouldRasterizeIOS: false,
      }),
    },
    streamsMainContentMovie: {
      paddingTop: Platform.OS === 'android' ? 10 : 15,
    },
    filterContainer: {
      paddingHorizontal: 12,
      paddingBottom: 8,
    },
    filterScroll: {
      flexGrow: 0,
    },
    filterChip: {
      backgroundColor: colors.elevation2,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 16,
      marginRight: 8,
      borderWidth: 0,
    },
    filterChipSelected: {
      backgroundColor: colors.primary,
    },
    filterChipText: {
      color: colors.highEmphasis,
      fontWeight: '600',
      letterSpacing: 0.1,
    },
    filterChipTextSelected: {
      color: colors.white,
      fontWeight: '700',
    },
    streamsContent: {
      flex: 1,
      width: '100%',
      zIndex: 2,
    },
    streamsContainer: {
      paddingHorizontal: 12,
      paddingBottom: 20,
      width: '100%',
    },
    streamGroup: {
      marginBottom: 24,
      width: '100%',
    },
    streamGroupTitle: {
      color: colors.highEmphasis,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 6,
      marginTop: 0,
      opacity: 0.9,
      backgroundColor: 'transparent',
    },
    noStreams: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    noStreamsText: {
      color: colors.textMuted,
      fontSize: 16,
      marginTop: 16,
    },
    noStreamsSubText: {
      color: colors.mediumEmphasis,
      fontSize: 14,
      marginTop: 8,
      textAlign: 'center',
    },
    addSourcesButton: {
      marginTop: 24,
      paddingHorizontal: 20,
      paddingVertical: 10,
      backgroundColor: colors.primary,
      borderRadius: 8,
    },
    addSourcesButtonText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '600',
    },
    streamsHeroContainer: {
      width: '100%',
      height: HERO_HEIGHT,
      marginBottom: 0,
      position: 'relative',
      backgroundColor: 'transparent',
      pointerEvents: 'box-none',
      zIndex: 1,
    },
    streamsHeroBackground: {
      width: '100%',
      height: '100%',
      backgroundColor: 'transparent',
    },
    streamsHeroGradient: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'flex-end',
      padding: 16,
      paddingBottom: 0,
    },
    streamsHeroContent: {
      width: '100%',
    },
    streamsHeroInfo: {
      width: '100%',
    },
    streamsHeroEpisodeNumber: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: 'bold',
      marginBottom: 2,
      textShadowColor: 'rgba(0,0,0,0.75)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    streamsHeroTitle: {
      color: colors.highEmphasis,
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 4,
      textShadowColor: 'rgba(0,0,0,0.75)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    streamsHeroOverview: {
      color: colors.mediumEmphasis,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 2,
      textShadowColor: 'rgba(0,0,0,0.75)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    streamsHeroMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 0,
    },
    streamsHeroReleased: {
      color: colors.mediumEmphasis,
      fontSize: 14,
      textShadowColor: 'rgba(0,0,0,0.75)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    streamsHeroRating: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 0,
    },
    tmdbLogo: {
      width: 20,
      height: 14,
    },
    imdbLogo: {
      width: 28,
      height: 15,
    },
    streamsHeroRatingText: {
      color: colors.highEmphasis,
      fontSize: 13,
      fontWeight: '700',
      marginLeft: 4,
    },
    streamsHeroRuntime: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    streamsHeroRuntimeText: {
      color: colors.mediumEmphasis,
      fontSize: 13,
      fontWeight: '600',
    },
    loadingContainer: {
      alignItems: 'center',
      paddingVertical: 24,
    },
    loadingText: {
      color: colors.primary,
      fontSize: 12,
      marginLeft: 4,
      fontWeight: '500',
    },
    footerLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
    },
    footerLoadingText: {
      color: colors.primary,
      fontSize: 12,
      marginLeft: 8,
      fontWeight: '500',
    },
    movieTitleContainer: {
      width: '100%',
      height: MOVIE_TITLE_HEIGHT,
      backgroundColor: 'transparent',
      pointerEvents: 'box-none',
      justifyContent: 'center',
      paddingTop: Platform.OS === 'android' ? 65 : 35,
    },
    movieTitleContent: {
      width: '100%',
      height: 80,
      alignItems: 'center',
      justifyContent: 'center',
    },
    movieLogo: {
      width: '100%',
      height: 80,
      maxWidth: SCREEN_WIDTH * 0.85,
    },
    movieTitle: {
      color: colors.highEmphasis,
      fontSize: 28,
      fontWeight: '900',
      textAlign: 'center',
      letterSpacing: -0.5,
      paddingHorizontal: 20,
    },
    sectionHeaderContainer: {
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    sectionHeaderContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sectionLoadingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    sectionLoadingText: {
      marginLeft: 8,
    },
    autoplayOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: 'rgba(0,0,0,0.8)',
      padding: 16,
      alignItems: 'center',
      zIndex: 10,
    },
    autoplayIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.elevation2,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 8,
    },
    autoplayText: {
      color: colors.primary,
      fontSize: 14,
      marginLeft: 8,
      fontWeight: '600',
    },
    activeScrapersContainer: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: 'transparent',
      marginHorizontal: 16,
      marginBottom: 4,
    },
    activeScrapersTitle: {
      color: colors.mediumEmphasis,
      fontSize: 12,
      fontWeight: '500',
      marginBottom: 6,
      opacity: 0.8,
    },
    activeScrapersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
    },
    backButtonContainerTablet: {
      zIndex: 3,
    },
    mobileFullScreenBackground: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    mobileNoBackdropBackground: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.darkBackground,
    },
    heroBlendOverlay: {
      position: 'absolute',
      top: 140,
      left: 0,
      right: 0,
      height: Platform.OS === 'android' ? 95 : 180,
      zIndex: 0,
      pointerEvents: 'none',
    },
    chip: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 12,
      marginRight: 6,
      marginBottom: 6,
      backgroundColor: colors.elevation2,
    },
    chipText: {
      color: colors.highEmphasis,
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
  });
